export const boardData = [
  //PRESIDENTS

  {
    name: "Rachel Tong",
    title: "Co-President",
    team: "Presidents",
    bio: "WICC introduced me to a close community of people who are not only passionate about computing but also extremely supportive and eager to help. I was first introduced to WICC freshman fall through the Lunch Bunch and Mentorship Program. Amidst the chaotic transition into college, those programs truly helped me ease into college and meet amazing upperclassmen and professors. I'm super excited to get more involved and meet more people!",
    netId: "rt387",
  },
  {
    name: "Jasmine Samadi",
    title: "Co-President",
    team: "Presidents",
    bio: "",
    netId: "jns222",
  },

  //OPERATIONS

  {
    name: "Victoria Varkonyi",
    title: "Co-Treasurer",
    team: "Operations",
    bio: "",
    netId: "vv229",
  },

  {
    name: "Gaby Castro",
    title: "Co-Treasurer",
    team: "Operations",
    bio: "",
    netId: "gc422",
  },
  {
    name: "Selena Liu",
    title: "Secretary",
    team: "Operations",
    bio: "",
    netId: "sl2663",
  },

  //CORPORATE
  {
    name: "Vicki Yang",
    title: "Vice President, Corporate Relations",
    team: "Corporate",
    bio: "",
    netId: "vzy3",
  },
  {
    name: "Nala Peng",
    title: "Corporate Relations Co-Director",
    team: "Corporate",
    bio: "In an ideal world I will be growing mushrooms.",
    netId: "kp426",
  },
  {
    name: "Lara Kulkarni",
    title: "Corporate Relations Co-Director",
    team: "Corporate",
    bio: "",
    netId: "lk427",
  },
  {
    name: "Hermione Bossolina",
    title: "Corporate Relations Co-Director",
    team: "Corporate",
    bio: "",
    netId: "hlb88",
  },
  {
    name: "Tanvi Namjoshi",
    title: "Alumni Relations Co-Director",
    team: "Corporate",
    bio: "",
    netId: "tkn24",
  },
  {
    name: "Reva Jariwala",
    title: "Alumni Relations Co-Director",
    team: "Corporate",
    bio: "",
    netId: "raj97",
  },

  //ACADEMIC
  {
    name: "Lauren Chan",
    title: "Vice President, Academic",
    team: "Academic",
    bio: "",
    netId: "lac348",
  },
  {
    name: "Tanisha Kore",
    title: "Faculty Relations Co-Director",
    team: "Academic",
    bio: "",
    netId: "tk494",
  },
  {
    name: "Sarah Young",
    title: "Faculty Relations Co-Director",
    team: "Academic",
    bio: "",
    netId: "sy398",
  },
  {
    name: "Meera Ramesh",
    title: "Career Development Co-Director",
    team: "Academic",
    bio: "Growing up, I internalized a lot of negative stereotypes about what types of people were meant for a career in tech, and these preconceptions pushed me away from considering the field despite my interest in problem solving. I entered Cornell as a biomedical engineer, but after attending a couple WICC events, I found myself a community of women in technology that didn't fit the stereotypes I thought to be true. WICC truly empowered me to feel confident in my eventual decision to pursue computer science. By being a career development co-director, I hope to spread this same empowerment and inclusivity to those who've felt the same way I did coming into college.",
    netId: "mr828",
  },
  {
    name: "Habiba Khan",
    title: "Career Development Director",
    team: "Academic",
    bio: "",
    netId: "hk692",
  },
  {
    name: "Neha Sunkara",
    title: "Underclassmen Outreach Director",
    team: "Academic",
    bio: "",
    netId: "ns597",
  },
  {
    name: "Jeanie Chan",
    title: "Underclassmen Outreach Director",
    team: "Academic",
    bio: "",
    netId: "jc2885",
  },
  //BRAND
  {
    name: "Ariani Gomez",
    title: "Vice President, Brand",
    team: "Brand",
    bio: "",
    netId: "amg374",
  },
  {
    name: "Uyen Hoang",
    title: "Technical Director",
    team: "Brand",
    bio: "Uyen is a cat and panda lover who passionate about Design, Tech, and the Written Word",
    netId: "umh4",
  },
  {
    name: "Selin Toker",
    title: "Publicity Director",
    team: "Brand",
    bio: "",
    netId: "st798",
  },
  {
    name: "Claire Tan",
    title: "Photography Director",
    team: "Brand",
    bio: "",
    netId: "ct556",
  },
  {
    name: "Kelly Ryoo",
    title: "Design Co-Director",
    team: "Brand",
    bio: "Kelly is a Computer Science major in the College of Arts and Sciences. As the social co-director, she enjoys planning events and socializing with new people. She also loves to do calligraphy, organize her spotify playlists, and read in her free time.",
    netId: "kyr5",
  },
  {
    name: "Lauren Jun",
    title: "Design Co-Director",
    team: "Brand",
    bio: "",
    netId: "lj295",
  },

  //OUTREACH
  {
    name: "Jessica Wang",
    title: "Vice President, Outreach",
    team: "Outreach",
    bio: "",
    netId: "jjw255",
  },

  {
    name: "Shreya Ponugoti",
    title: "Outreach Co-Director",
    team: "Outreach",
    bio: "",
    netId: "sp843",
  },
  {
    name: "Jennifer Ai",
    title: "Outreach Co-Director",
    team: "Outreach",
    bio: "",
    netId: "jla292",
  },
  {
    name: "Miriam Alex",
    title: "Outreach Co-Director",
    team: "Outreach",
    bio: "",
    netId: "mta63",
  },

  //COMMUNITY

  {
    name: "Jacqueline Chin",
    title: "Vice President, Community",
    team: "Community",
    bio: "",
    netId: "jc2745",
  },
  {
    name: "Krishna Patel",
    title: "Social Co-Director",
    team: "Community",
    bio: "",
    netId: "khp42",
  },
  {
    name: "Goretti Muriithi",
    title: "Social Co-Director",
    team: "Community",
    bio: "",
    netId: "gm552",
  },
  {
    name: "Victoria Whittle",
    title: "Mentorship Co-Director",
    team: "Community",
    bio: "",
    netId: "vnw3",
  },
  {
    name: "Sreya Jonnalagadda",
    title: "Mentorship Co-Director",
    team: "Community",
    bio: "",
    netId: "sj652",
  },
  {
    name: "Jarin Rahman",
    title: "Allyship Co-Director",
    team: "Community",
    bio: "",
    netId: "jsr296",
  },
  {
    name: "Arshia Agrawal",
    title: "Allyship Co-Director",
    team: "Community",
    bio: "",
    netId: "aa2443",
  },

  //ADVISORS

  {
    name: "Tina Ou",
    title: "Advisor, Co-President",
    team: "Advisors",
    bio: "",
    netId: "to98",
    year: "2024",
    major: "Computer Science",
  },
  {
    name: "Aarushi Singh",
    title: "Advisor, VP Academic/Corporate Relations/Faculty Relations",
    team: "Advisors",
    bio: "",
    netId: "as2585",
    year: "2024",
    major: "Computer Science",
  },
  {
    name: "Amida Akpan",
    title: "Advisor, Social",
    team: "Advisors",
    bio: "",
    netId: "aua6",
    year: "2025",
    major: "Computer Science",
  },
  {
    name: "Kelly Chan",
    title: "Advisor",
    team: "Advisors",
    bio: "",
    netId: "khc74",
  },
  {
    name: "Tiffany Lee",
    title: "Advisor, Mentorship",
    team: "Advisors",
    bio: "",
    netId: "tl559",
  },
  {
    name: "Neha Malepati",
    title: "Advisor",
    team: "Advisors",
    bio: "",
    netId: "nm458",
  },
  {
    name: "Shreeya Indap",
    title: "Advisor",
    team: "Advisors",
    bio: "",
    netId: "si223",
  },
  {
    name: "Stephanie Ginting",
    title: "Advisor, Design",
    team: "Advisors",
    bio: "",
    netId: "sag292",
  },
  {
    name: "Mikayla Lin",
    title: "Advisor",
    team: "Advisors",
    bio: "",
    netId: "ml953",
  },
  {
    name: "Julia Papp",
    title: "Advisor",
    team: "Advisors",
    bio: "",
    netId: "jgp88",
  },
  {
    name: "Jennifer Gu",
    title: "Advisor",
    team: "Advisors",
    bio: "",
    netId: "jg2368",
  },
  {
    name: "Ananya Seelam",
    title: "Advisor, Outreach",
    team: "Advisors",
    bio: "I became interested in computer science when I took my high school's Introduction to Computer Science course. I've loved math and logic ever since I can remember and computer science was a way I could apply those interests to solve real world problems. Coming to Cornell, I knew that I wanted to share my passion for computer science with other high school students who may not have had the same exposure to it that I've had. This led me to becoming a volunteer for the Girls Who Code program that WICC hosts for local middle and high school students. Now, as an Outreach Director, I help run this program which cultivates an inclusive and supportive environment for students to explore their interests in computer science!",
    netId: "as2759",
  },
  {
    name: "Rejoice Hu",
    title: "Advisor, VP Corporate, Alumni Relations, Corporate Relations",
    team: "Advisors",
    bio: "Before coming into college, I had no exposure to computer science. When I took my first programming course in freshman year, I remember being blown away by how powerfully versatile CS is and how it placed the power to make an impact, however big or small, right at my fingertips. But given my interests in medicine / healthcare, I struggled for a long time to reconcile these two amazing but seemingly very different worlds, until I found Information Science, a major that added that human element I always wanted in technology! As a student new to CIS as well as Cornell during the pandemic, WICC’s strong community of women helped me feel included and empowered—I felt like I belonged and had people I could connect with. Seeing how much WICC has helped me grow and how WICC was consistently behind many of the most impactful events of my new Cornell experience, I am so grateful for this opportunity to pay it forward and create that same impact on my fellow Cornellians and beyond!",
    netId: "rh635",
  },
  {
    name: "Ruike Liang",
    title: "Advisor, Secretary/Alumni/Faculty Relations",
    team: "Advisors",
    bio: "",
    netId: "rl582",
  },
];
