export const boardData = [
  //PRESIDENTS

  {
    name: "Rachel Tong",
    title: "Co-President",
    team: "Presidents",
    bio: "WICC introduced me to a close community of people who are not only passionate about computing but also extremely supportive and eager to help. I was first introduced to WICC freshman fall through the Lunch Bunch and Mentorship Program. Amidst the chaotic transition into college, those programs truly helped me ease into college and meet amazing upperclassmen and professors. I'm super excited to get more involved and meet more people!",
    netId: "rt387",
  },
  {
    name: "Jasmine Samadi",
    title: "Co-President",
    team: "Presidents",
    bio: "WICC is the first place that made me feel like I belong in the computing field. After years of trying to find my path and being discouraged, I finally found a welcoming and supportive community of women and non-binary people in tech. I am so grateful for the warmth and guidance given to me from WICC members. I can only hope to extend a similar arm and welcome more people whose shoes I was in. ",
    netId: "jns222",
  },

  //OPERATIONS

  {
    name: "Victoria Varkonyi",
    title: "Co-Treasurer",
    team: "Operations",
    bio: "",
    netId: "vv229",
  },

  {
    name: "Gaby Castro",
    title: "Co-Treasurer",
    team: "Operations",
    bio: "",
    netId: "gc422",
  },
  {
    name: "Selena Liu",
    title: "Secretary",
    team: "Operations",
    bio: "",
    netId: "sl2663",
  },

  //CORPORATE
  {
    name: "Vicki Yang",
    title: "Vice President, Corporate Relations",
    team: "Corporate",
    bio: "",
    netId: "vzy3",
  },
  {
    name: "Nala Peng",
    title: "Corporate Relations Co-Director",
    team: "Corporate",
    bio: "In an ideal world I will be growing mushrooms.",
    netId: "kp426",
  },
  {
    name: "Lara Kulkarni",
    title: "Corporate Relations Co-Director",
    team: "Corporate",
    bio: "",
    netId: "lk427",
  },
  {
    name: "Hermione Bossolina",
    title: "Corporate Relations Co-Director",
    team: "Corporate",
    bio: "",
    netId: "hlb88",
  },
  {
    name: "Tanvi Namjoshi",
    title: "Alumni Relations Co-Director",
    team: "Corporate",
    bio: "",
    netId: "tkn24",
  },
  {
    name: "Reva Jariwala",
    title: "Alumni Relations Co-Director",
    team: "Corporate",
    bio: "",
    netId: "raj97",
  },

  //ACADEMIC
  {
    name: "Lauren Chan",
    title: "Vice President, Academic",
    team: "Academic",
    bio: "Lauren is a junior from Princeton, NJ majoring in Information Science with minors in Business and Nutritional Sciences. This past summer, Lauren worked as a Digital Marketing Analytics Intern at Tarte Cosmetics. She first joined WICC in Fall 2022 under WICC's mentorship program as an ILR major looking to get more into the tech space and later joined board the following semester as Underclassmen Outreach Co-Director. After switching majors, she is now Vice President of the Academic Team for this semester. She has experience being an external and internal transfer and is involved in a business fraternity on campus along with Grub Ventures, a food and agriculture tech-focused venture capital club. In her free time, Lauren enjoys staying active, exploring national parks, trying out new recipes, and listening to true crime podcasts.",
    netId: "lac348",
  },
  {
    name: "Tanisha Kore",
    title: "Faculty Relations Co-Director",
    team: "Academic",
    bio: "",
    netId: "tk494",
  },
  {
    name: "Sarah Young",
    title: "Faculty Relations Co-Director",
    team: "Academic",
    bio: "Sarah is a junior majoring in Computer Science. She is passionate in creating technology that can help others. She joined WICC because she loves how empowering WICC is and the community that it offered! In her free time, she enjoys sleeping, watching Netflix, and dancing. ",
    netId: "sy398",
  },
  {
    name: "Meera Ramesh",
    title: "Career Development Co-Director",
    team: "Academic",
    bio: "Growing up, I internalized a lot of negative stereotypes about what types of people were meant for a career in tech, and these preconceptions pushed me away from considering the field despite my interest in problem solving. I entered Cornell as a biomedical engineer, but after attending a couple WICC events, I found myself a community of women in technology that didn't fit the stereotypes I thought to be true. WICC truly empowered me to feel confident in my eventual decision to pursue computer science. By being a career development co-director, I hope to spread this same empowerment and inclusivity to those who've felt the same way I did coming into college. WICC has helped me understand how to foster a more inclusive environment in technology, and I am so grateful for the inspiring people I've met through it. As a board member, I can only hope to empower more underrepresented communities to pursue a career in tech. Outside of WICC, I'm interested in dance, music, and art.",
    netId: "mr828",
  },
  {
    name: "Habiba Khan",
    title: "Career Development Director",
    team: "Academic",
    bio: "",
    netId: "hk692",
  },
  {
    name: "Neha Sunkara",
    title: "Underclassmen Outreach Director",
    team: "Academic",
    bio: "",
    netId: "ns597",
  },
  {
    name: "Jeanie Chan",
    title: "Underclassmen Outreach Director",
    team: "Academic",
    bio: "Hi! I'm Jeanie, a CS major in the College of Engineering. I joined WICC as a freshman and have gained a lot from joining programs and attending events. WICC is such a supportive and welcoming community :) ",
    netId: "jc2885",
  },
  //BRAND
  {
    name: "Ariani Gomez",
    title: "Vice President, Brand",
    team: "Brand",
    bio: "",
    netId: "amg374",
  },
  {
    name: "Uyen Hoang",
    title: "Technical Director",
    team: "Brand",
    bio: "Uyen is a cat and panda lover who passionate about Design, Tech, and the Written Word",
    netId: "umh4",
  },
  {
    name: "Selin Toker",
    title: "Publicity Director",
    team: "Brand",
    bio: "I'm studying Computer Science in the College of Engineering, and I come from Istanbul, Turkey. Since joining WICC, I've connected with some really kind people and collaborated with others who share my interests about computing. As the publicity director, I enjoy spreading the word about WICC, which is all about creating a supportive community that brings together people from diverse backgrounds. Outside of all this, I enjoy reading, listening to music, watching romcoms, and taking lots of photos in my free time!",
    netId: "st798",
  },
  {
    name: "Claire Tan",
    title: "Photography Director",
    team: "Brand",
    bio: "When I arrived at Cornell, the world of computing was like a distant realm to me and things like joining clubs, finding opportunities, and choosing classes made me feel lost. WICC has WICC has allowed me to join a welcoming community of driven, passionate individuals who have helped me in my journey. The camaraderie of this community has made the complex seem approachable and the unknown less daunting. I’m excited to continue forging new connections in WICC and further exploring the exciting opportunities this community offers!",
    netId: "ct556",
  },
  {
    name: "Kelly Ryoo",
    title: "Design Co-Director",
    team: "Brand",
    bio: "Kelly is a Computer Science major in the College of Arts and Sciences. As the social co-director, she enjoys planning events and socializing with new people. She also loves to do calligraphy, organize her spotify playlists, and read in her free time.",
    netId: "kyr5",
  },
  {
    name: "Lauren Jun",
    title: "Design Co-Director",
    team: "Brand",
    bio: "",
    netId: "lj295",
  },

  //OUTREACH
  {
    name: "Jessica Wang",
    title: "Vice President, Outreach",
    team: "Outreach",
    bio: "",
    netId: "jjw255",
  },

  {
    name: "Shreya Ponugoti",
    title: "Outreach Co-Director",
    team: "Outreach",
    bio: "",
    netId: "sp843",
  },
  {
    name: "Jennifer Ai",
    title: "Outreach Co-Director",
    team: "Outreach",
    bio: "I joined WICC because I wanted to be a part of a supportive group of people within the computing and information science community. I am so glad to be a part of the outreach team because I have had the pleasure of working with so many wonderful peers and teaching younger students who are interested in computing. ",
    netId: "jla292",
  },
  {
    name: "Miriam Alex",
    title: "Outreach Co-Director",
    team: "Outreach",
    bio: "When I look back on my first semester, it’s the small, warm moments that seem to peek out from my memory. When I first arrived at Cornell, I sorely lacked a community; like many others, I wasn’t sure who I could spend time with, how to manage a quickly intensifying schedule, or what the correct steps to take moving forward could be. However, in the beginning of my first year, I remember a friend dragging me along to Phillips Hall, promising Insomnia cookies if we could sit through a meeting. Coincidentally, it was an interest meeting for the WICC mentorship. After meeting the mentors, we were struck by how vibrant and motivated everyone was; it felt like the beginning of something larger than ourselves. To put it simply, WICC inspired me to do more and provided me with the resources to do it. Through my time as an outreach co-director, I hope that I can provide a fraction of that community to Cornell and greater Ithaca. ",
    netId: "mta63",
  },

  //COMMUNITY

  {
    name: "Jacqueline Chin",
    title: "Vice President, Community",
    team: "Community",
    bio: "",
    netId: "jc2745",
  },
  {
    name: "Krishna Patel",
    title: "Social Co-Director",
    team: "Community",
    bio: "I joined WICC as a freshman fall semester. Cornell is a huge university, but WICC provided the supportive and caring community that I wanted! WICC allowed me to meet people with similar interests, get advice and assistance from upperclassmen, and opened me up to a lot of amazing opportunities on campus!",
    netId: "khp42",
  },
  {
    name: "Goretti Muriithi",
    title: "Social Co-Director",
    team: "Community",
    bio: "Hi! I am a sophomore in the College of Arts & Sciences studying Computer Science. When I got to Cornell, I was uncertain about my future in computing, since I did not have a lot of experience coding in high school. However, I found a very supporting and active community in WICC. My mentors and friends in WICC helped me feel more confident in my abilities and helped me find resources in order to excel in my classes. I joined WICC E-Board in order to give back and encourage gender minorities to enter the computing field. ",
    netId: "gm552",
  },
  {
    name: "Victoria Whittle",
    title: "Mentorship Co-Director",
    team: "Community",
    bio: "",
    netId: "vnw3",
  },
  {
    name: "Sreya Jonnalagadda",
    title: "Mentorship Co-Director",
    team: "Community",
    bio: "Attending a STEM high school where I was often the one of the few girls in the classes, I often felt unheard and unconfident. I knew coming into college that I wanted to join a community supporting women as they navigate the tech space and WICC was just that! I look forward to contributing to this empowering and inclusive community and watching it blossom. In my free time I love to rock climb!",
    netId: "sj652",
  },
  {
    name: "Jarin Rahman",
    title: "Allyship Co-Director",
    team: "Community",
    bio: "Jamming to k-pop, blowing bubbles, making each other beaded bracelets – all while laughing and exchanging amusing stories about our lives so far – wasn't something I expected to happen at WICC Away. I didn’t think I’d become entangled in the lives of my newly-met peers and share our wildest dreams and fears. Being in a community of people who were similar to me reminded me of how in most male dominated spaces, it's hard to reach out for help and feel included because of prejudice and judgements. I wanted to become a part of the WICC community that promotes inclusiveness and makes those new to the computing field feel safe. ",
    netId: "jsr296",
  },
  {
    name: "Arshia Agrawal",
    title: "Allyship Co-Director",
    team: "Community",
    bio: "One quote that always stuck with me was from Reshma Saujani, founder of Girls Who Code. In an interview, she shared an anecdote from her time teaching young coders: When young boys had buggy code, they asked, “What’s wrong with my code?” But when the young girls in her class had the same issue, their first instinct was to ask, “What’s wrong with me?” As a gender minority entering a male-dominated field, it can be intimidating - especially when we are raised doubting our abilities. WICC is so important to me because it empowers me to gain confidence in myself and is just an incredible community of people who are always there to uplift me and lead me towards opportunities I never would have found without their support. I hope to help give back and empower the next group of young women/gender minorities navigating their way through CS at Cornell. And outside of WICC, I love singing & songwriting, doing jigsaw puzzles, and writing poetry! :)",
    netId: "aa2443",
  },

  //ADVISORS

  {
    name: "Tina Ou",
    title: "Advisor, Co-President",
    team: "Advisors",
    bio: "",
    netId: "to98",
    year: "2024",
    major: "Computer Science",
  },
  {
    name: "Aarushi Singh",
    title: "Advisor, VP Academic/Corporate Relations/Faculty Relations",
    team: "Advisors",
    bio: "",
    netId: "as2585",
    year: "2024",
    major: "Computer Science",
  },
  {
    name: "Amida Akpan",
    title: "Advisor, Social",
    team: "Advisors",
    bio: "",
    netId: "aua6",
    year: "2025",
    major: "Computer Science",
  },
  {
    name: "Kelly Chan",
    title: "Advisor",
    team: "Advisors",
    bio: "",
    netId: "khc74",
  },
  {
    name: "Tiffany Lee",
    title: "Advisor, Mentorship",
    team: "Advisors",
    bio: "",
    netId: "tl559",
  },
  {
    name: "Neha Malepati",
    title: "Advisor",
    team: "Advisors",
    bio: "",
    netId: "nm458",
  },
  {
    name: "Shreeya Indap",
    title: "Advisor",
    team: "Advisors",
    bio: "",
    netId: "si223",
  },
  {
    name: "Stephanie Ginting",
    title: "Advisor, Design",
    team: "Advisors",
    bio: "",
    netId: "sag292",
  },
  {
    name: "Mikayla Lin",
    title: "Advisor",
    team: "Advisors",
    bio: "",
    netId: "ml953",
  },
  {
    name: "Julia Papp",
    title: "Advisor",
    team: "Advisors",
    bio: "",
    netId: "jgp88",
  },
  {
    name: "Jennifer Gu",
    title: "Advisor",
    team: "Advisors",
    bio: "",
    netId: "jg2368",
  },
  {
    name: "Ananya Seelam",
    title: "Advisor, Outreach",
    team: "Advisors",
    bio: "I became interested in computer science when I took my high school's Introduction to Computer Science course. I've loved math and logic ever since I can remember and computer science was a way I could apply those interests to solve real world problems. Coming to Cornell, I knew that I wanted to share my passion for computer science with other high school students who may not have had the same exposure to it that I've had. This led me to becoming a volunteer for the Girls Who Code program that WICC hosts for local middle and high school students. Now, as an Outreach Director, I help run this program which cultivates an inclusive and supportive environment for students to explore their interests in computer science!",
    netId: "as2759",
  },
  {
    name: "Rejoice Hu",
    title: "Advisor, VP Corporate, Alumni Relations, Corporate Relations",
    team: "Advisors",
    bio: "Before coming into college, I had no exposure to computer science. When I took my first programming course in freshman year, I remember being blown away by how powerfully versatile CS is and how it placed the power to make an impact, however big or small, right at my fingertips. But given my interests in medicine / healthcare, I struggled for a long time to reconcile these two amazing but seemingly very different worlds, until I found Information Science, a major that added that human element I always wanted in technology! As a student new to CIS as well as Cornell during the pandemic, WICC’s strong community of women helped me feel included and empowered—I felt like I belonged and had people I could connect with. Seeing how much WICC has helped me grow and how WICC was consistently behind many of the most impactful events of my new Cornell experience, I am so grateful for this opportunity to pay it forward and create that same impact on my fellow Cornellians and beyond!",
    netId: "rh635",
  },
  {
    name: "Ruike Liang",
    title: "Advisor, Secretary/Alumni/Faculty Relations",
    team: "Advisors",
    bio: "",
    netId: "rl582",
  },
];
